### ISSUE TITLE
Performance issue of the provided Gaussian model. 

### ISSUE THREAD

**Issue by lifuguan** [DensoITLab/Fed3DGS#2]
Hi, 
I've tested the provided pre-trained model on Rubble. It seems the performance is pretty weird.
The PSNR  is 14dB, which is quite low.
![image](https://github.com/DensoITLab/Fed3DGS/assets/17793134/977daea6-fc0c-4f75-af95-bc85da981268)
![image](https://github.com/DensoITLab/Fed3DGS/assets/17793134/0ee815c4-bc87-4e65-9316-461d30e7a592)

**Comment by perrying** [comment]
I think you installed `diff-gaussian-rasterization` from the original repo, not our repository.
Gaussians near the target camera are not rendered in your rendered image, and this is because the original `diff-gaussian-rasterization` ignores such Gaussians.
https://github.com/graphdeco-inria/diff-gaussian-rasterization/blob/59f5f77e3ddbac3ed9db93ec2cfe99ed6c5d121d/cuda_rasterizer/auxiliary.h#L154

We modify it in our repo.
https://github.com/DensoITLab/Fed3DGS/blob/9d9ca8d5429ed3e86c284fb5406ed941642fe768/gaussian-splatting/submodules/diff-gaussian-rasterization/cuda_rasterizer/auxiliary.h#L154

Please reinstall `diff-gaussian-rasterization` from our repo.

**Comment by lifuguan** [comment]
Thank you! Appreciate a lot!
